@startuml
class Robot {
// Status includes {idle active fault}
    +id: int
    +type: int
    +size: boolean
    +time: int
    +failure_rate: float
}

class SmallRobot {
    +id
    +type
    +size
    +time
    +failure_rate
}

class LargeRobot {
    +id
    +type
    +size
    +time
    +failure_rate
}

interface Sweeper {
    +sweep()
}

interface Vacuum {
    +vacuum()
}

interface Mapper {
    +map()
}


Robot <|-- SmallRobot
Robot <|-- LargeRobot

SmallRobot --> Sweeper
SmallRobot --> Vacuum
SmallRobot --> Mapper

LargeRobot --> Sweeper
LargeRobot --> Vacuum
LargeRobot --> Mapper
@enduml